services : 
  postgres : 
    image : postgres:17
    environment:
      POSTGRES_USER : cricket
      POSTGRES_PASSWORD : cricket
      POSTGRES_DB : cricket-scorer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: